//! Who may talk to this gateway: the web login for a browser, or one minted
//! token for the client an embedded gateway was started by.
//!
//! A process has exactly one of them ([`GatewayAuth`], chosen at startup), which
//! is what keeps each mode free of the other's machinery.
//!
//! **The login.** TOML strings carry a bcrypt hash verbatim — its `$./` alphabet
//! needs no escaping: `[server].site_passwd` is plain `username:bcrypt_hash`
//! (generated by `remotex gen-passwd <username>`), `/api/auth/login` verifies a
//! username/password pair against it and mints a session token, and everything
//! guarded (the rest of `/api/*`, `/ws`) requires that token in the cookie.
//! Sessions live in memory only — a server restart logs every browser out,
//! which is fine for a single-user program.
//!
//! **The token.** `remotex serve-embedded` has no user to ask and nowhere to keep
//! a credential: it is started for one managed browser instance. So it mints an
//! [`EmbeddedToken`], hands it to its parent down a pipe (see [`crate::embedded`]),
//! and takes it in the same `remotex_session` cookie a login would have set. The
//! parent control plane seeds it as an HttpOnly cookie on the instance subdomain,
//! which lets one page load carry it to `/api/*` and to the WebSocket upgrades alike
//! — a header cannot reach either from inside a document. Such a gateway still refuses `/api/auth/login`
//! and `/api/auth/logout`: there is no credential to check and no session to end.

use std::collections::HashMap;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use anyhow::Context as _;
#[cfg(feature = "embedded-gateway")]
use base64::Engine as _;
#[cfg(feature = "embedded-gateway")]
use rand::RngExt as _;

/// Name of the auth session cookie.
pub const COOKIE_NAME: &str = "remotex_session";

/// Default bcrypt cost for `gen-passwd` (the crate default).
pub const DEFAULT_COST: u32 = bcrypt::DEFAULT_COST;

/// Sliding session lifetime: every validated request pushes the expiry out.
const SESSION_TTL: Duration = Duration::from_secs(6 * 60 * 60);

/// The parsed `[server].site_passwd` credential: the one username allowed to
/// log in and the bcrypt hash of its password.
#[derive(Clone)]
pub struct SitePasswd {
    username: String,
    hash: String,
}

// Manual Debug so an AppConfig dump never prints the hash.
impl std::fmt::Debug for SitePasswd {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SitePasswd")
            .field("username", &self.username)
            .finish_non_exhaustive()
    }
}

impl SitePasswd {
    /// Parse the credential: `username:bcrypt_hash`, verbatim.
    pub fn parse(credential: &str) -> anyhow::Result<Self> {
        let (username, hash) = credential
            .trim()
            .split_once(':')
            .context("site_passwd must be username:bcrypt_hash")?;
        anyhow::ensure!(!username.is_empty(), "site_passwd username is empty");
        anyhow::ensure!(
            ["$2a$", "$2b$", "$2y$"].iter().any(|p| hash.starts_with(p)),
            "site_passwd hash for user {username:?} is not bcrypt (want $2a$/$2b$/$2y$)"
        );
        Ok(Self {
            username: username.to_owned(),
            hash: hash.to_owned(),
        })
    }

    /// The username allowed to log in (for startup logging).
    pub fn username(&self) -> &str {
        &self.username
    }

    /// Check a login attempt. A wrong username still burns a bcrypt verify so
    /// the two rejections don't differ by timing.
    pub fn verify(&self, username: &str, password: &str) -> bool {
        let password_ok = bcrypt::verify(password, &self.hash).unwrap_or(false);
        password_ok && username == self.username
    }
}

/// How this process decides that a request may proceed at all.
///
/// One of the two, fixed at startup: a `serve` gateway can only be a
/// [`Self::Login`] and a `serve-embedded` one can only be a [`Self::Token`]. That
/// is the point of an enum here rather than two optional fields — neither mode
/// carries a way in that it does not use, and `require_auth` in
/// [`crate::server`] matches on this and on nothing else.
#[derive(Clone, Debug)]
pub enum GatewayAuth {
    /// A web login: the `[server].site_passwd` credential, the `remotex_session`
    /// cookie, and the [`AuthSessions`] behind it.
    Login(SitePasswd),
    /// One token, minted at startup and given to the client that started this
    /// gateway, which presents it as the same `remotex_session` cookie a login
    /// would have set. `/api/auth/login` and `/api/auth/logout` refuse on such a
    /// gateway: there is nothing to log in to and nothing to end.
    #[cfg(feature = "embedded-gateway")]
    Token(EmbeddedToken),
}

impl GatewayAuth {
    /// The login credential when this is a deployed gateway. A managed gateway
    /// has no interactive login endpoint.
    pub fn login(&self) -> Option<&SitePasswd> {
        match self {
            Self::Login(site_passwd) => Some(site_passwd),
            #[cfg(feature = "embedded-gateway")]
            Self::Token(_) => None,
        }
    }

    /// Validate the cookie using the only authentication scheme compiled into
    /// and selected for this process.
    pub fn authenticates(&self, sessions: &AuthSessions, presented: &str) -> bool {
        match self {
            Self::Login(_) => sessions.validate(presented),
            #[cfg(feature = "embedded-gateway")]
            Self::Token(expected) => expected.matches(presented),
        }
    }
}

/// The secret an embedded gateway and its one client share: 32 random bytes,
/// base64url, minted per launch.
///
/// Deliberately not hashed the way [`SitePasswd`] is. A hash protects a credential
/// at rest against whoever reads where it rests, and this one never rests: it is
/// generated in memory, written once to a pipe held by the process that spawned
/// this one, and gone when this one exits. There is also nobody to be slow for —
/// bcrypt's cost exists to make guessing a *human's* password expensive, and 32
/// random bytes are not guessable at any cost.
#[cfg(feature = "embedded-gateway")]
#[derive(Clone)]
pub struct EmbeddedToken(String);

// Manual Debug so a config dump — which carries the whole `GatewayAuth` — cannot
// print the one secret that would let anything drive the remote.
#[cfg(feature = "embedded-gateway")]
impl std::fmt::Debug for EmbeddedToken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("EmbeddedToken(…)")
    }
}

#[cfg(feature = "embedded-gateway")]
impl EmbeddedToken {
    /// How many random bytes the token carries.
    const BYTES: usize = 32;

    /// Mint a fresh token from the OS random source.
    pub fn generate() -> Self {
        let mut bytes = [0u8; Self::BYTES];
        rand::rng().fill(&mut bytes);
        Self(base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes))
    }

    /// The value to hand the client, and the only place it is readable.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Whether a presented value is this token, without leaking *where* it stops
    /// matching.
    ///
    /// The length is not a secret — every token this mints is the same length — so
    /// a mismatched length answers immediately. The bytes are, so they are folded
    /// into one accumulator rather than compared with an early return.
    pub fn matches(&self, presented: &str) -> bool {
        let expected = self.0.as_bytes();
        let presented = presented.as_bytes();
        if expected.len() != presented.len() {
            return false;
        }
        let mut difference = 0u8;
        for (a, b) in expected.iter().zip(presented) {
            difference |= a ^ b;
        }
        difference == 0
    }
}

/// Generate a `site_passwd` value (the `gen-passwd` subcommand; tests pass a
/// low cost to keep logins fast).
pub fn generate(username: &str, password: &str, cost: u32) -> anyhow::Result<String> {
    anyhow::ensure!(!username.is_empty(), "username must not be empty");
    anyhow::ensure!(!username.contains(':'), "username must not contain ':'");
    anyhow::ensure!(!password.is_empty(), "password must not be empty");
    let hash = bcrypt::hash(password, cost).context("bcrypt hash failed")?;
    Ok(format!("{username}:{hash}"))
}

/// In-memory auth sessions: token → expiry, with a sliding TTL. The map only
/// ever holds this single user's handful of logins, so expired entries are
/// swept opportunistically on create/validate instead of by a timer.
pub struct AuthSessions {
    sessions: Mutex<HashMap<String, Instant>>,
    ttl: Duration,
}

impl Default for AuthSessions {
    fn default() -> Self {
        Self::with_ttl(SESSION_TTL)
    }
}

impl AuthSessions {
    fn with_ttl(ttl: Duration) -> Self {
        Self {
            sessions: Mutex::new(HashMap::new()),
            ttl,
        }
    }

    /// Mint a session token after a successful login.
    pub fn create(&self) -> String {
        let token = uuid::Uuid::new_v4().to_string();
        let mut sessions = self.sessions.lock().unwrap();
        let now = Instant::now();
        sessions.retain(|_, expiry| *expiry > now);
        sessions.insert(token.clone(), now + self.ttl);
        token
    }

    /// True when the token names a live session; refreshes the sliding expiry.
    pub fn validate(&self, token: &str) -> bool {
        let mut sessions = self.sessions.lock().unwrap();
        let now = Instant::now();
        match sessions.get_mut(token) {
            Some(expiry) if *expiry > now => {
                *expiry = now + self.ttl;
                true
            }
            Some(_) => {
                sessions.remove(token);
                false
            }
            None => false,
        }
    }

    /// Drop a session (logout).
    pub fn invalidate(&self, token: &str) {
        self.sessions.lock().unwrap().remove(token);
    }
}

/// Extract this app's session token from a request's `Cookie` header.
pub fn token_from_headers(headers: &axum::http::HeaderMap) -> Option<String> {
    let cookies = headers.get(axum::http::header::COOKIE)?.to_str().ok()?;
    cookies.split(';').find_map(|pair| {
        let (name, value) = pair.trim().split_once('=')?;
        (name == COOKIE_NAME).then(|| value.to_owned())
    })
}

#[cfg(test)]
mod tests {
    use axum::http::{HeaderMap, HeaderValue, header};

    use super::*;

    // bcrypt's minimum cost, so tests don't burn CPU on real key stretching.
    const TEST_COST: u32 = 4;

    #[test]
    fn generate_parse_verify_roundtrip() {
        let encoded = generate("admin", "hunter2", TEST_COST).unwrap();
        let site = SitePasswd::parse(&encoded).unwrap();
        assert_eq!(site.username(), "admin");
        assert!(site.verify("admin", "hunter2"));
        assert!(!site.verify("admin", "wrong"));
        assert!(!site.verify("mallory", "hunter2"), "username must match too");
    }

    #[test]
    fn generate_rejects_bad_input() {
        assert!(generate("", "pw", TEST_COST).is_err());
        assert!(generate("a:b", "pw", TEST_COST).is_err(), "':' would corrupt the format");
        assert!(generate("admin", "", TEST_COST).is_err());
    }

    #[test]
    fn parse_rejects_malformed_credentials() {
        let msg = |s: &str| format!("{:#}", SitePasswd::parse(s).unwrap_err());
        assert!(msg("just-a-username").contains("username:bcrypt_hash"));
        assert!(msg(":$2b$04$hash").contains("username is empty"));
        assert!(msg("admin:$1$legacy$hash").contains("bcrypt"), "only bcrypt hashes");
    }

    #[test]
    fn sessions_validate_refresh_and_invalidate() {
        let sessions = AuthSessions::default();
        let token = sessions.create();
        assert!(sessions.validate(&token));
        assert!(!sessions.validate("no-such-token"));
        sessions.invalidate(&token);
        assert!(!sessions.validate(&token));
    }

    #[test]
    fn expired_sessions_are_rejected() {
        let sessions = AuthSessions::with_ttl(Duration::ZERO);
        let token = sessions.create();
        assert!(!sessions.validate(&token), "a zero-TTL session is born expired");
    }

    /// A minted token matches itself and nothing else, including the near misses a
    /// hand-rolled constant-time compare could get wrong: a prefix, an extension,
    /// and the empty string.
    #[cfg(feature = "embedded-gateway")]
    #[test]
    fn an_embedded_token_matches_only_itself() {
        let token = EmbeddedToken::generate();
        assert!(token.matches(token.as_str()));
        assert!(!token.matches(""));
        assert!(!token.matches(&token.as_str()[..token.as_str().len() - 1]), "a prefix");
        assert!(!token.matches(&format!("{}x", token.as_str())), "an extension");
        assert!(!token.matches(EmbeddedToken::generate().as_str()), "another token");
    }

    /// Two launches never share a secret, and the encoding is URL-safe base64 so
    /// the value can sit in a header untouched.
    #[cfg(feature = "embedded-gateway")]
    #[test]
    fn embedded_tokens_are_fresh_and_header_safe() {
        let (a, b) = (EmbeddedToken::generate(), EmbeddedToken::generate());
        assert_ne!(a.as_str(), b.as_str());
        // 32 bytes, base64 without padding.
        assert_eq!(a.as_str().len(), 43, "{}", a.as_str());
        assert!(
            a.as_str()
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'),
            "{}",
            a.as_str()
        );
    }

    /// The one secret that would drive the remote must not be printable by
    /// accident: `AppConfig` derives Debug and carries this.
    #[cfg(feature = "embedded-gateway")]
    #[test]
    fn an_embedded_token_is_not_in_its_debug_output() {
        let token = EmbeddedToken::generate();
        let auth = GatewayAuth::Token(token.clone());
        for rendered in [format!("{token:?}"), format!("{auth:?}")] {
            assert!(!rendered.contains(token.as_str()), "{rendered}");
        }
        assert!(auth.login().is_none(), "a token gateway has no login");
    }

    #[test]
    fn token_is_found_among_other_cookies() {
        let mut headers = HeaderMap::new();
        headers.insert(
            header::COOKIE,
            HeaderValue::from_str(&format!("other=1; {COOKIE_NAME}=tok-123; x=y")).unwrap(),
        );
        assert_eq!(token_from_headers(&headers).as_deref(), Some("tok-123"));

        let mut headers = HeaderMap::new();
        headers.insert(header::COOKIE, HeaderValue::from_static("other=1"));
        assert_eq!(token_from_headers(&headers), None);
        assert_eq!(token_from_headers(&HeaderMap::new()), None);
    }
}
